In [1]:
import pandas as pd
import re 
import plotly.express as px
import datetime as dt
import numpy as np

In [2]:
df = pd.read_csv("..\\data\\survey_results.csv")




matriz = pd.read_csv("..\\data\\matriz_ids.csv")

In [3]:
df['createdDate'] = pd.to_datetime(df['createdDate'])
df['year'] = df['createdDate'].dt.year
df['month'] = df['createdDate'].dt.month
df['day'] = df['createdDate'].dt.day


matriz['createdDate'] = pd.to_datetime(matriz['createdDate'])
matriz['year'] = matriz['createdDate'].dt.year
matriz['month'] = matriz['createdDate'].dt.month
matriz['day'] = matriz['createdDate'].dt.day

In [4]:
dezembro = df[(df['month'] == 12) & (df['year'] == 2024)]
dezembro
# dezembro = pd.to_datetime(dezembro['createdDate']).dt.strftime('%Y-%m')

dezembro_matriz = matriz[(matriz['month'] == 12) & (matriz['year'] == 2024)]

In [5]:
dezembro_atendimentos_por_dia = dezembro.groupby('day').size().reset_index(name='Atendimentos')

In [6]:
dezembro_atendimentos_por_dia.describe()

             day  Atendimentos
count  25.000000     25.000000
mean   15.840000    107.080000
std     8.905429     77.081623
min     2.000000     27.000000
25%     9.000000     40.000000
50%    16.000000     55.000000
75%    23.000000    160.000000
max    31.000000    250.000000

In [7]:
dezembro_atendimentos_por_dia['Atendimentos'].sum()

np.int64(2677)

In [8]:
dezembro

,ticket_id,createdDate,status,category,resolvedInFirstCall,urgency,chatWaitingTime,chatTalkTime,serviceFirstLevel,serviceSecondLevel,...,lifeTimeWorkingTime,organization,analyst,createdBy,type,value,comment,year,month,day
22466,2059128,2024-12-02 11:08:11.477757700,Resolvido,Erro,True,Baixa - COM correcao,6.0,1.0,Service Manager,VR Midia,...,61.0,VRAM - SUPER BARANDA,Rodolfo Joaquim,Marcelo Silva,S/A,S/N,NaN,2024,12,2
22467,2059138,2024-12-02 11:10:39.709741300,Resolvido,Configuracao,True,Baixa - SEM correcao,8.0,0.0,Concentrador Travado,Consistencia,...,19.0,VRAP - MERCADAO REAL MACAPA,Luis Souza,Marllison Wendel,S/A,S/N,NaN,2024,12,2
22468,2059157,2024-12-02 11:13:59.847866700,Resolvido,Duvida,True,Baixa - COM correcao,2.0,0.0,Repositorio NFCe/Sat,VR Master - PDV,...,25.0,VRPA - O CORINGAO,Francisco Netto,Maycon Mota,3,10,BOM ATENDIMENTO.,2024,12,2
22469,2059215,2024-12-02 11:25:43.934531800,Resolvido,Duvida,True,Baixa - COM correcao,3.0,0.0,PDV - Consistencia - Finalizar Consistencia,VR Master,...,20.0,VRPA - SUPERMERCADOS VERDURAO,Paulo Rodrigues,Jonas Lopes da Silva,3,10,NaN,2024,12,2
22470,2059253,2024-12-02 11:31:59.132478900,Resolvido,Configuracao,True,Baixa - SEM correcao,9.0,2.0,Estoque- Gerenciamento Estoque - Dias de Venda...,VR Master,...,130.0,VRPA - O CORINGAO,Luis Souza,Rodrigo Oliveira,3,10,NaN,2024,12,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28156,2092024,2024-12-31 13:35:21.036790900,Resolvido,Duvida,True,Baixa - SEM correcao,7.0,6.0,Nota Fiscal - Saida,VR Master,...,7.0,VRPA - SPAZZIO SUPERMERCADO,Francisco Netto,Isaura Maria,3,10,NaN,2024,12,31
28157,2092082,2024-12-31 14:03:36.392181500,Resolvido,Duvida,True,Baixa - COM correcao,5.0,16.0,Aliquota ICMS,VR Master - Fiscal,...,17.0,VRPA - SPAZZIO SUPERMERCADO,Paulo Rodrigues,Isaura Maria,3,10,NaN,2024,12,31
28158,2092140,2024-12-31 14:35:37.181349500,Resolvido,Inatividade,True,Baixa - SEM correcao,5.0,11.0,Inatividade,Inatividade,...,11.0,VRPA - SPAZZIO SUPERMERCADO,Luis Souza,Isaura Maria,S/A,S/N,NaN,2024,12,31
28159,2092200,2024-12-31 15:35:09.042164300,Resolvido,Duvida,True,Baixa - SEM correcao,2.0,10.0,Entrada,NF-e,...,10.0,VRPA - SPAZZIO SUPERMERCADO,Luis Souza,Maisa Vieira,3,10,NaN,2024,12,31
28160,2092256,2024-12-31 16:58:19.996551100,Resolvido,Duvida,True,Baixa - SEM correcao,12.0,13.0,Exportacao Balanca,VR Master - ADM,...,20.0,VRPA - O CORINGAO - L01 - (G599),Francisco Netto,Ilana Bastos,3,10,NaN,2024,12,31

In [9]:
dezembro_avaliados = dezembro.query("value != 'S/N'")

In [10]:
total_dezembro_avaliados = len(dezembro_avaliados)
total_dezembro_avaliados

1913

In [11]:
dezembro_avaliados['value'] = dezembro_avaliados['value'].astype(int)

C:\Users\VR Belém - PDV\AppData\Local\Temp\ipykernel_10908\1510200121.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dezembro_avaliados['value'] = dezembro_avaliados['value'].astype(int)

In [12]:
dezembro_positivas = len(dezembro_avaliados[dezembro_avaliados['value'] >= 7])
dezembro_positivas

1814

In [13]:
dezembro_positivas

1814

In [14]:
satisfacao = round(dezembro_positivas / total_dezembro_avaliados, 2) * 100

In [15]:
dezembro_avaliados['value'].describe()

count    1913.000000
mean        9.396759
std         1.772621
min         0.000000
25%        10.000000
50%        10.000000
75%        10.000000
max        10.000000
Name: value, dtype: float64

In [16]:
dezembro_avaliados[dezembro_avaliados['value'] == 0].count()

ticket_id              33
createdDate            33
status                 33
category               33
resolvedInFirstCall    33
urgency                33
chatWaitingTime        33
chatTalkTime           33
serviceFirstLevel      33
serviceSecondLevel     29
serviceThirdLevel      29
lifeTimeWorkingTime    33
organization           33
analyst                33
createdBy              33
type                   33
value                  33
comment                13
year                   33
month                  33
day                    33
dtype: int64

In [17]:
total_dezembro_atendimentos = len(dezembro)

In [18]:
conversao = round(total_dezembro_avaliados / total_dezembro_atendimentos, 2) * 100
conversao

71.0

In [19]:
dezembro_matriz

,ticket_id,createdDate,ownerTeam,status,category,urgency,serviceFirstLevel,serviceSecondLevel,owner.businessName,owner,analista,time,year,month,day
4913,2059370,2024-12-02 12:01:13.721597200,Software House,Resolvido,Requisição de Serviço - Dúvida,Baixa - COM correção,Administrativo,Administrativo / Conciliador / Financeiro,Karina Paula,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,2
4914,2059942,2024-12-02 14:32:55.731614300,Software House,Resolvido,Dúvida,Baixa - COM correção,Saída,Nota Fiscal,Marcelo Santos,NaN,Luis Souza,SKYONE - Unidade Belem,2024,12,2
4915,2060862,2024-12-03 11:13:33.807516400,Software House,Resolvido,Requisição de Serviço - Dúvida,Baixa - COM correção,Financeiro,Administrativo / Conciliador / Financeiro,Renan Pacheco,NaN,Paulo Rodrigues,SKYONE - Unidade Belem,2024,12,3
4916,2062043,2024-12-03 18:34:51.075434000,Software House,Resolvido,Dúvida,Baixa - COM correção,Saída,Nota Fiscal,Marcelo Santos,NaN,Paulo Rodrigues,SKYONE - Unidade Belem,2024,12,3
4917,2063008,2024-12-04 13:42:23.723632800,Software House,Resolvido,Incidente - Falha na Aplicação,Baixa - COM correção,Operacional PDV,VR PDV,Felipe Ramos,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001,2090675,2024-12-30 13:09:55.047178200,Software House,Resolvido,Requisição de Serviço - Dúvida,Baixa - COM correção,Cadastro - Impressora,VR Emissor Etiqueta,Gustavo Farias,NaN,Luis Souza,SKYONE - Unidade Belem,2024,12,30
5002,2091080,2024-12-30 16:42:52.830954100,Software House,Concluído,Requisição de Serviço - Dúvida,Baixa - COM correção,Recuperação de backup,VR Backup,Gustavo Farias,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,30
5003,2091104,2024-12-30 16:58:09.033924300,SERVIÇOS- Matriz,Concluído,Requisição de Serviço - Dúvida,Baixa - COM correção,Recuperação de backup,VR Backup,Gabriel Camargo,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,30
5004,2091325,2024-12-30 18:30:40.637553500,Software House,Resolvido,Incidente - Falha na Aplicação,Baixa - COM correção,Autorizador - Credito Rotativo,VR Autorizador,Jefferson Buzato,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,30
5005,2091408,2024-12-30 19:06:52.171836800,Software House,Resolvido,Requisição de Serviço - Dúvida,Baixa - COM correção,Financeiro - Contas a Receber - Verba - Sell -...,VR Master,Gustavo Farias,NaN,Francisco Netto,SKYONE - Unidade Belem,2024,12,30

In [20]:
dezembro["value_numeric"] = pd.to_numeric(dezembro["value"], errors="coerce")

daily_stats = dezembro.groupby(["analyst", "day"]).agg(
    total_atendimentos=("value", "count"),
    total_convertido_por_dia=("value_numeric", lambda x: x.notna().sum()),
    total_não_convertidos_por_dia=("value", lambda x: (x =="S/N").sum()),
    total_resolvidos_na_hora=("resolvedInFirstCall", lambda x: (x == True).sum()),
    total_resolvidos_depois=('resolvedInFirstCall', lambda x: (x == False).sum()),
    notas_positivas=("value_numeric", lambda x: (x >= 7).sum()),
    notas_negativas=("value_numeric", lambda x: (x < 7).sum()),
).reset_index()

daily_stats["satisfacao_diaria"] = np.where(
    daily_stats["total_convertido_por_dia"] > 0,
    (daily_stats["notas_positivas"] / daily_stats["total_convertido_por_dia"]) * 100,
    0
)

daily_stats["conversao_diaria"] = (daily_stats["total_convertido_por_dia"] / 
                                   daily_stats["total_atendimentos"]) * 100



daily_stats_analyst_matriz = dezembro_matriz.groupby(["analista", "day"]).agg(
    total_atendimentos=("ticket_id", "count"),
).reset_index()

C:\Users\VR Belém - PDV\AppData\Local\Temp\ipykernel_10908\769114823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dezembro["value_numeric"] = pd.to_numeric(dezembro["value"], errors="coerce")

In [21]:
daily_stats_analyst_matriz

           analista  day  total_atendimentos
0      Adriel Sousa   10                   1
1      Adriel Sousa   12                   2
2      Adriel Sousa   16                   1
3      Adriel Sousa   18                   1
4      Adriel Sousa   26                   1
5      Adriel Sousa   27                   2
6   Francisco Netto    2                   1
7   Francisco Netto    4                   3
8   Francisco Netto    5                   1
9   Francisco Netto    6                   1
10  Francisco Netto    9                   2
11  Francisco Netto   13                   2
12  Francisco Netto   19                   1
13  Francisco Netto   20                   2
14  Francisco Netto   23                   2
15  Francisco Netto   24                   1
16  Francisco Netto   26                   1
17  Francisco Netto   27                   1
18  Francisco Netto   30                   4
19       Luis Souza    2                   1
20       Luis Souza    6                   2
21       Luis Souza    9                   6
22       Luis Souza   10                   2
23       Luis Souza   11                   2
24       Luis Souza   12                   1
25       Luis Souza   13                   1
26       Luis Souza   16                   2
27       Luis Souza   17                   2
28       Luis Souza   18                   1
29       Luis Souza   20                   1
30       Luis Souza   23                   2
31       Luis Souza   24                   1
32       Luis Souza   26                   1
33       Luis Souza   30                   1
34  Paulo Rodrigues    3                   2
35  Paulo Rodrigues    4                   3
36  Paulo Rodrigues    5                   1
37  Paulo Rodrigues   10                   1
38  Paulo Rodrigues   12                   1
39  Paulo Rodrigues   13                   1
40  Paulo Rodrigues   16                   1
41  Paulo Rodrigues   17                   2
42  Paulo Rodrigues   18                   2
43  Paulo Rodrigues   20                   2
44  Paulo Rodrigues   26                   1
45  Rodolfo Joaquim    4                   1
46  Rodolfo Joaquim   10                   1
47  Rodolfo Joaquim   16                   1
48  Rodolfo Joaquim   17                   3
49  Rodolfo Joaquim   19                   2
50  Rodolfo Joaquim   20                   1
51  Rodolfo Joaquim   24                   1
52  Rodolfo Joaquim   26                   2
53  Rodolfo Joaquim   30                   1
54     Ronald Lopes    5                   1
55     Ronald Lopes    9                   1
56     Ronald Lopes   11                   1
57     Ronald Lopes   16                   1
58     Ronald Lopes   17                   2
59     Ronald Lopes   18                   1

In [22]:
daily_stats['total_atendimentos'].mean()

np.float64(25.018691588785046)

In [23]:
daily_stats['satisfacao_diaria'].mean()

np.float64(88.97000935964654)

In [24]:
daily_stats['conversao_diaria'].describe()

count    107.000000
mean      70.341253
std       24.165947
min        0.000000
25%       60.000000
50%       70.000000
75%       87.083333
max      100.000000
Name: conversao_diaria, dtype: float64